//each route represents a page
export const LANDING= "/home";
export const HOME = "/";
export const ABOUT = "/about";
export const MAP = "/map";
export const ACCOUNT = "/account";
export const SIGNUP = "/signup";
export const SIGNOUT = "/signout";
export const SIGN_IN = "/signin";
export const PROJECT = "/projects";
export const ARTICLES = "/articles";
export const PASSWORD_FORGET = "/passwordforget";
export const DIRECTORY = "/directory";
export const TEAMMEMBER = "/directory/:id"; 
// export const LINKGITHUB = '/linkgithub';
export const WORLD = "/world";
// export const UNDERCONSTRUCT = "/directory/:construct";
export const PROFILE = "/directory/:username"
export const INDIVIDUAL_VIEW = "/articles/:articleId";
// export const USERPROFILE= "/userprofile";
