export const LANDING = "/";
export const HOME = "/home"
export const ABOUT = "/about";
/*export const CREATEARTICLE = '/createarticle'*/
export const ACCOUNT = "/account";
export const SIGNUP = "/signup";
export const SIGN_IN = "/signin";
export const PROJECT = "/projects";
export const PASSWORD_FORGET = "/pw-forget";
export const INDIVIDUAL_VIEW = "/articles/:articleId";
export const ARTICLES ="/articles";
